#-------------------------------------------------------------------------------
# Name:        module1
# Purpose:
#
# Author:      jlegind
#
# Created:     06-05-2013
# Copyright:   (c) jlegind 2013
# Licence:     <your licence>
#-------------------------------------------------------------------------------
#!/usr/bin/env python
# -*- coding: utf-8 -*-

def main():
##    my_list = [1,2,3,4,'g','h']
##    for j in my_list:
##        print "(%s)%s" % (my_list.index(j),  j),
##    print
##    ln = len(my_list)
##    print ln
##    my_list.reverse()
##    for j in my_list:
##        print "(%s)%s" % (my_list.index(j),  j),
##    print
##    for j in my_list[:3:]:
##        print j,

##    my_set = set("jkl")
##    print my_set
##    my_set = set(['e','r','t'])
##    print my_set
##
    list1 = ["ANDORRA","UNITED ARAB EMIRATES","AFGHANISTAN","ANTIGUA AND BARBUDA","ANGUILLA","ALBANIA","ARMENIA","NETHERLANDS ANTILLES","ANGOLA","ANTARCTICA","ARGENTINA","AMERICAN SAMOA","AUSTRIA","AUSTRALIA","ARUBA","ALAND ISLANDS","AZERBAIJAN","BOSNIA AND HERZEGOVINA","BARBADOS","BANGLADESH","BELGIUM","BURKINA FASO","BULGARIA","BAHRAIN","BURUNDI","BENIN","SAINT BARTHÉLEMY","BERMUDA","BRUNEI DARUSSALAM","BOLIVIA, PLURINATIONAL STATE OF","BONAIRE, SINT EUSTATIUS AND SABA","BRAZIL","BAHAMAS","BHUTAN","BOUVET ISLAND","BOTSWANA","BELARUS","BELIZE","CANADA","COCOS (KEELING) ISLANDS","CONGO, THE DEMOCRATIC REPUBLIC OF THE","CENTRAL AFRICAN REPUBLIC","CONGO","SWITZERLAND","CÔTE D'IVOIRE","COOK ISLANDS","CHILE","CAMEROON","CHINA","COLOMBIA","COSTA RICA","CUBA","CAPE VERDE","CURAÇAO","CHRISTMAS ISLAND","CYPRUS","CZECH REPUBLIC","GERMANY","DJIBOUTI","DENMARK","DOMINICA","DOMINICAN REPUBLIC","ALGERIA","ECUADOR","ESTONIA","EGYPT","WESTERN SAHARA","ERITREA","SPAIN","ETHIOPIA","FINLAND","FIJI","FALKLAND ISLANDS (MALVINAS)","MICRONESIA, FEDERATED STATES OF","FAROE ISLANDS","FRANCE","GABON","UNITED KINGDOM","GRENADA","GEORGIA","FRENCH GUIANA","GUERNSEY","GHANA","GIBRALTAR","GREENLAND","GAMBIA","GUINEA","GUADELOUPE","EQUATORIAL GUINEA","GREECE","SOUTH GEORGIA AND THE SOUTH SANDWICH ISLANDS","GUATEMALA","GUAM","GUINEA-BISSAU","GUYANA","HONG KONG","HEARD ISLAND AND MCDONALD ISLANDS","HONDURAS","CROATIA","HAITI","HUNGARY","INDONESIA","IRELAND","ISRAEL","ISLE OF MAN","INDIA","BRITISH INDIAN OCEAN TERRITORY","IRAQ","IRAN, ISLAMIC REPUBLIC OF","ICELAND","ITALY","JERSEY","JAMAICA","JORDAN","JAPAN","KENYA","KYRGYZSTAN","CAMBODIA","KIRIBATI","COMOROS","SAINT KITTS AND NEVIS","KOREA, DEMOCRATIC PEOPLE'S REPUBLIC OF","KOREA, REPUBLIC OF","KUWAIT",
"CAYMAN ISLANDS","KAZAKHSTAN","LAO PEOPLE'S DEMOCRATIC REPUBLIC","LEBANON","SAINT LUCIA","LIECHTENSTEIN","SRI LANKA","LIBERIA","LESOTHO","LITHUANIA","LUXEMBOURG","LATVIA","LIBYA","MOROCCO","MONACO","MOLDOVA, REPUBLIC OF","MONTENEGRO","SAINT MARTIN (FRENCH PART)","MADAGASCAR","MARSHALL ISLANDS","MACEDONIA, THE FORMER YUGOSLAV REPUBLIC OF","MALI","MYANMAR","MONGOLIA","MACAO","NORTHERN MARIANA ISLANDS","MARTINIQUE","MAURITANIA","MONTSERRAT","MALTA","MAURITIUS","MALDIVES","MALAWI","MEXICO","MALAYSIA","MOZAMBIQUE","NAMIBIA","NEW CALEDONIA","NIGER","NORFOLK ISLAND","NIGERIA","NICARAGUA","NETHERLANDS","NORWAY","NEPAL","NAURU","NIUE","NEW ZEALAND","OMAN","PANAMA","PERU","FRENCH POLYNESIA","PAPUA NEW GUINEA","PHILIPPINES","PAKISTAN","POLAND","SAINT PIERRE AND MIQUELON","PITCAIRN","PUERTO RICO","PALESTINE, STATE OF","PORTUGAL","PALAU","PARAGUAY","QATAR","RÉUNION","ROMANIA","SERBIA","RUSSIAN FEDERATION","RWANDA","SAUDI ARABIA","SOLOMON ISLANDS","SEYCHELLES","SUDAN","SWEDEN","SINGAPORE","SAINT HELENA, ASCENSION AND TRISTAN DA CUNHA","SLOVENIA","SVALBARD AND JAN MAYEN","SLOVAKIA","SIERRA LEONE","SAN MARINO","SENEGAL","SOMALIA","SURINAME","SOUTH SUDAN","SAO TOME AND PRINCIPE","EL SALVADOR","SINT MAARTEN (DUTCH PART)","SYRIAN ARAB REPUBLIC","SWAZILAND","TURKS AND CAICOS ISLANDS","CHAD","FRENCH SOUTHERN TERRITORIES","TOGO","THAILAND","TAJIKISTAN","TOKELAU","TIMOR-LESTE","TURKMENISTAN","TUNISIA","TONGA","TURKEY","TRINIDAD AND TOBAGO","TUVALU","CHINESE TAIPEI","TANZANIA, UNITED REPUBLIC OF","UKRAINE","UGANDA","UNITED STATES MINOR OUTLYING ISLANDS","UNITED STATES","URUGUAY","UZBEKISTAN","HOLY SEE (VATICAN CITY STATE)","SAINT VINCENT AND THE GRENADINES","VENEZUELA, BOLIVARIAN REPUBLIC OF","VIRGIN ISLANDS, BRITISH","VIRGIN ISLANDS, U.S.","VIET NAM","VANUATU","WALLIS AND FUTUNA","SAMOA","YEMEN","MAYOTTE","SOUTH AFRICA","ZAMBIA","ZIMBABWE"]
    set_1 = set()
    set_2 = set()

    for j in list1:
        #j.decode('utf8')
        set_1.add(j)

    list2 = ["ANDORRA","UNITED ARAB EMIRATES","AFGHANISTAN","ANTIGUA AND BARBUDA","ANGUILLA","ALBANIA","ARMENIA","NETHERLANDS ANTILLES","ANGOLA","ANTARCTICA","ARGENTINA","AMERICAN SAMOA","AUSTRIA","AUSTRALIA","ARUBA","ALAND ISLANDS","AZERBAIJAN","BOSNIA AND HERZEGOVINA","BARBADOS","BANGLADESH","BELGIUM","BURKINA FASO","BULGARIA","BAHRAIN","BURUNDI","BENIN","SAINT BARTH?LEMY","BERMUDA","BRUNEI DARUSSALAM","BOLIVIA","BRAZIL","BAHAMAS","BHUTAN","BOUVET ISLAND","BOTSWANA","BELARUS","BELIZE","CANADA","COCOS (KEELING) ISLANDS","CONGO, THE DEMOCRATIC REPUBLIC OF THE","CENTRAL AFRICAN REPUBLIC","CONGO","SWITZERLAND","COTE D'IVOIRE","COOK ISLANDS","CHILE","CAMEROON","CHINA","COLOMBIA","COSTA RICA","CUBA","CAPE VERDE","CURA€AO","CHRISTMAS ISLAND","CYPRUS","CZECH REPUBLIC","GERMANY","DJIBOUTI","DENMARK","DOMINICA","DOMINICAN REPUBLIC","ALGERIA","ECUADOR","ESTONIA","EGYPT","WESTERN SAHARA","ERITREA","SPAIN","ETHIOPIA","FINLAND","FIJI","FALKLAND ISLANDS (MALVINAS)","MICRONESIA, FEDERATED STATES OF","FAROE ISLANDS","FRANCE","GABON","UNITED KINGDOM","GRENADA","GEORGIA","FRENCH GUIANA","GUERNSEY","GHANA","GIBRALTAR","GREENLAND","GAMBIA","GUINEA","GUADELOUPE","EQUATORIAL GUINEA","GREECE","SOUTH GEORGIA AND THE SOUTH SANDWICH ISLANDS","GUATEMALA","GUAM","GUINEA-BISSAU","GUYANA","HONG KONG","HEARD ISLAND AND MCDONALD ISLANDS","HONDURAS","CROATIA","HAITI","HUNGARY","INDONESIA","IRELAND","ISRAEL","ISLE OF MAN","INDIA","BRITISH INDIAN OCEAN TERRITORY","IRAQ","IRAN, ISLAMIC REPUBLIC OF","ICELAND","ITALY","JERSEY","JAMAICA","JORDAN","JAPAN","KENYA","KYRGYZSTAN","CAMBODIA","KIRIBATI","COMOROS","SAINT KITTS AND NEVIS","KOREA, DEMOCRATIC PEOPLE'S REPUBLIC OF","KOREA, REPUBLIC OF","KUWAIT",
"CAYMAN ISLANDS","KAZAKHSTAN","LAO PEOPLE'S DEMOCRATIC REPUBLIC","LEBANON","SAINT LUCIA","LIECHTENSTEIN","SRI LANKA","LIBERIA","LESOTHO","LITHUANIA","LUXEMBOURG","LATVIA","LIBYAN ARAB JAMAHIRIYA","MOROCCO","MONACO","MOLDOVA, REPUBLIC OF","MONTENEGRO","SAINT MARTIN (FRENCH PART)","MADAGASCAR","MARSHALL ISLANDS","MACEDONIA, THE FORMER YUGOSLAV REPUBLIC OF","MALI","MYANMAR","MONGOLIA","MACAO","NORTHERN MARIANA ISLANDS","MARTINIQUE","MAURITANIA","MONTSERRAT","MALTA","MAURITIUS","MALDIVES","MALAWI","MEXICO","MALAYSIA","MOZAMBIQUE","NAMIBIA","NEW CALEDONIA","NIGER","NORFOLK ISLAND","NIGERIA","NICARAGUA","NETHERLANDS","NORWAY","NEPAL","NAURU","NIUE","NEW ZEALAND","OMAN","PANAMA","PERU","FRENCH POLYNESIA","PAPUA NEW GUINEA","PHILIPPINES","PAKISTAN","POLAND","SAINT PIERRE AND MIQUELON","PITCAIRN","PUERTO RICO","PALESTINIAN TERRITORY, OCCUPIED","PORTUGAL","PALAU","PARAGUAY","QATAR","REUNION","ROMANIA","SERBIA","RUSSIAN FEDERATION","RWANDA","SAUDI ARABIA","SOLOMON ISLANDS","SEYCHELLES","SUDAN","SWEDEN","SINGAPORE","SAINT HELENA","SLOVENIA","SVALBARD AND JAN MAYEN","SLOVAKIA","SIERRA LEONE","SAN MARINO","SENEGAL","SOMALIA","SURINAME","SOUTH SUDAN","SAO TOME AND PRINCIPE","EL SALVADOR","SINT MAARTEN (DUTCH PART)","SYRIAN ARAB REPUBLIC","SWAZILAND","TURKS AND CAICOS ISLANDS","CHAD","FRENCH SOUTHERN TERRITORIES","TOGO","THAILAND","TAJIKISTAN","TOKELAU","TIMOR-LESTE","TURKMENISTAN","TUNISIA","TONGA","TURKEY","TRINIDAD AND TOBAGO","TUVALU","CHINESE TAIPEI","TANZANIA, UNITED REPUBLIC OF","UKRAINE","UGANDA","UNITED STATES MINOR OUTLYING ISLANDS","UNITED STATES","URUGUAY","UZBEKISTAN","HOLY SEE (VATICAN CITY STATE)","SAINT VINCENT AND THE GRENADINES","VENEZUELA","VIRGIN ISLANDS, BRITISH","VIRGIN ISLANDS, U.S.","VIET NAM","VANUATU","WALLIS AND FUTUNA","SAMOA","YEMEN","MAYOTTE","SOUTH AFRICA","ZAMBIA","ZIMBABWE"]

    for j in list2:
        #j.decode('utf8')
        set_2.add(j)


##    set_1 = set(['læk','køl'])
##    set_2 = set(['køl','kew','kål','kil'])
##    print set_1 - set_2
##
    for j in (set_1 - set_2):
        print j.decode('utf8')
##        #print j
##
##    u1 = 'gørålü'
##    print u1.decode('utf8')


if __name__ == '__main__':
    main()
